name: Windows MSI

on:
  workflow_dispatch:
    inputs:
      test-release:
        description: "Test release"
        required: false
        default: false
        type: boolean
  push:
    branches:
      - '**'
    tags:
      - '0.19.0'

jobs:
  build-windows-msi:
    runs-on: windows-2022
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
          fetch-tags: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up MSVC Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install Qt 6
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.7.2'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2022_64'
          cache: true
          modules: 'qtbase qttools qtdeclarative qttranslations'

      - name: Install WiX Toolset
        uses: crazy-max/ghaction-chocolatey@v3
        with:
          args: install wixtoolset --yes --no-progress

      - name: Verify tools
        shell: pwsh
        run: |
          msbuild /version
          candle.exe -?
          light.exe -?

      - name: Set version (tag or dev)
        id: setver
        shell: pwsh
        run: |
          if ($env:GITHUB_REF_TYPE -eq 'tag') {
            $ver = $env:GITHUB_REF_NAME
          } else {
            $base = ''
            if (Test-Path VERSION) {
              $base = (Get-Content VERSION -Raw).Trim()
            }
            if (-not $base) { $base = '0.0.0' }
            $sha = $env:GITHUB_SHA.Substring(0,7)
            $ver = "$base-dev+$sha"
          }
          echo "SYNERGY_VERSION=$ver" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Prepare Python venv and requirements
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          python scripts/setup_venv.py

      - name: Install build dependencies
        shell: pwsh
        run: |
          python scripts/install_deps.py

      - name: Configure (CMake windows-release preset)
        shell: pwsh
        run: |
          cmake -B build --preset=windows-release -DBUILD_INSTALLER=ON -DCMAKE_BUILD_TYPE=Release -DQT_PATH="$env:Qt6_DIR"

      - name: Build binaries
        shell: pwsh
        run: |
          cmake --build build -j 8 --config Release

      - name: Package MSI
        env:
          SYNERGY_VERSION: ${{ env.SYNERGY_VERSION }}
        shell: pwsh
        run: |
          python scripts/package.py

      - name: Upload MSI artifact
        uses: actions/upload-artifact@v4
        with:
          name: synergy-msi-${{ env.SYNERGY_VERSION }}
          path: dist/*.msi
          if-no-files-found: error



